<a href="https://colab.research.google.com/github/deepanshuchoudhary448/45-day-of-python/blob/main/day26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# polynomial regression
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# data
df = pd.DataFrame({
    "Experience" :[1,2,3,4,5]
})

x = df
y = [10,20,50,90,150]

# poly feature
poly = PolynomialFeatures(degree=2)
x_poly = poly.fit_transform(x)
print(x_poly)


# model
model = LinearRegression()
model.fit(x_poly,y)

# prediction
input_data = int(input('Enter the experience:'))
new_data = pd.DataFrame({
    'Experience':[input_data]
})

# convert new data to poly
u_new_data = poly.fit_transform(new_data)
predicted_data = model.predict(u_new_data)
print(predicted_data)

[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]
 [ 1.  5. 25.]]


In [ ]:
# linear reg
import numpy as np
import pandas as pd
from sklearn.linear_linear_model import LinearRegression
df = pd.DataFrame({
    "label":[1,2,3,4,5]

})
x = df
y = [10,20,50,90,150]

# model
model = LinearRegression



In [ ]:
# poly reg
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linar_model import LinearRegression

df = pd.DataFrame({
    "label":[1,2,3,4,5]
})
x = df
y = [10,20,50,90,150]
# poly  convert
poly = PolynomialFeatures(degree=3)
x_poly = poly.fit_transform(x)
# model
model = LinearRegression()
model.fit (x_poly,y)
#predict
input data = int(input("enter the label:"))
new_data = pd.DataFrame({
    "label":[input_data]

})
# input data to pay
u_new_data = poly.fit_transform(new_data)
#prediction
predicted_data = model.predict(u_new_data)
print(predicted_data[0])

In [ ]:
# poly regression
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

df=pd.DataFrame({
    "label":[1,2,3,4,5]
})
x=df
y=[10,20,50,90,150]

# Polynomial Features
poly = PolynomialFeatures(degree=3)
x_poly = poly.fit_transform(x)


#model
model=LinearRegression()
model.fit(x_poly,y)

#predict
input_data=int(input("enter the label "))
new_data=pd.DataFrame({
    "label":[input_data]
})


#input data to poly
u_new_data=poly.fit_transform(new_data)


#prediction
new_poly = poly.transform(new_data)   # transform() only

prediction = model.predict(new_poly)
print(pre_data[0])
plt.plot(x_poly,new_data)
plt.show()

In [ ]:
# classification
import numpy as np
impor pandas as pd
from sklearn.tree import Decision TreeClassifier

df = pd.DataFrame ({
    "weight": [120,140,150,170]
    "size":[6,7,7,8]
})
x = df
y = [ "Apple","Apple","Orange","Orange"]
#model
model = DecisionTreeClassifier()
model.fit(x,y)
# predection data
input_weight = int(int('enter the weight:'))
input_size = int(input("enter the size :"))
new_data = pd.DataFrame


#predection
predicted_data = model.prdict(new_data)
print(predicted_data[0])


In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

# Data
df = pd.DataFrame({
    "weight": [120, 140, 150, 170],
    "size": [6, 7, 7, 8]
})

# Features
x = df

# Target
y = ["Apple", "Apple", "Orange", "Orange"]

# Model
model = DecisionTreeClassifier()
model.fit(x, y)

# Prediction Input
input_weight = int(input("Enter the weight: "))
input_size = int(input("Enter the size: "))

new_data = pd.DataFrame({
    "weight": [input_weight],
    "size": [input_size]
})

# Prediction
predicted_data = model.predict(new_data)

print("Predicted Fruit:", predicted_data[0])

In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier,plot_tree
import matplotlib.pyplot as plt


# Dataset
df = pd.DataFrame({
    "Marks": [20, 35, 40, 50, 60, 75, 90]
})

# Features
x = df

# Target
y = ["Fail", "Fail", "Pass", "Pass", "Pass", "Pass", "Pass"]

# Model
model = DecisionTreeClassifier()
model.fit(x, y)

# User Input
marks = int(input("Enter your marks: "))

new_data = pd.DataFrame({
    "Marks": [marks]
})

# Prediction
result = model.predict(new_data)

print("Result:", result[0])
# Decision Tree Graph
plt.figure(figsize=(8,5))

plot_tree(
    model,
    feature_names=["Marks"],
    class_names=["Fail", "Pass"],
    filled=True,
    rounded=True
)

plt.show()

In [ ]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
import pandas as pd

X = pd.DataFrame({
    "Hours": [1, 2, 3, 4, 5, 6]
})

y = [0, 0, 0, 1, 1, 1]

model = LogisticRegression()

model.fit(X, y)
# new data
new_data = pd.DataFrame({
    "Hours":[7]
})

print(model.predict(new_data))